version: '3.8'

services:
  nginx:
    container_name: bot_nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bot
  php:
    container_name: bot_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: always
    environment:
      APP_ENV: prod
    volumes:
      - ./:/var/www/html
    networks:
      - bot

  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      POSTGRES_DB: database
      POSTGRES_PASSWORD: /run/secrets/db_password
      POSTGRES_USER: /run/secrets/db_user
    ports:
      - "5432:5432"
    volumes:
      - ./docker/pg-data:/var/lib/postgresql/data:rw
    secrets:
      - db_password
      - db_user

secrets:
  db_user:
    file: db_user.txt
  db_password:
    file: db_password.txt

networks:
  bot:
    driver: bridge
