version: '3'

services:
###> doctrine/doctrine-bundle ###

  php:
    environment:
      APP_ENV: prod
    volumes:
      - ./:/var/www/html

  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

