version: '3'

services:
  nginx:
    container_name: bot_nginx
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bot
  php:
    container_name: bot_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: always
    environment:
      APP_ENV: dev
      PHP_IDE_CONFIG: serverName=bot_docker
    volumes:
      - ./:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - bot

  database:
    container_name: bot_db
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data:rw
    ports:
      - "5430:5432"
    environment:
      POSTGRES_DB: database
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: admin
    networks:
      - bot

volumes:
  pg_data:

networks:
  bot:
    driver: bridge
